#!/bin/bash
# Variable definitions for ROUTER
export EXTERNAL_IP_ROUTER="88.99.213.79"
export EXTERNAL_INTERFACE_ROUTER="ens18"
export SSH_INTERNAL_PORT_ROUTER="666"
export SSH_EXTERNAL_PORT_ROUTER="666"  # The external port for SSH

export ALLOWED_IPS_ROUTER=("138.199.59.0/24" "45.134.212.0/24" "85.221.131.0/24")  # <--- Replace with your allowed IPs

# Clear existing rules (use with caution!)
sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X

# Set default policies (crucial for security)
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD DROP  # Default to DROP for security
sudo iptables -P OUTPUT ACCEPT

# Allow established and related connections
sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Block all other incoming UDP traffic
sudo iptables -A INPUT -p udp --dport 111 -j REJECT

# Block all other outgoing UDP traffic (optional)
sudo iptables -A INPUT -p udp ! --dport 53 -j REJECT

# NAT and Port Mapping
sudo iptables -A INPUT -p tcp --dport 881 -j ACCEPT
sudo iptables -t nat -A POSTROUTING -o $EXTERNAL_INTERFACE_ROUTER -j MASQUERADE
sudo iptables -A FORWARD -i $EXTERNAL_INTERFACE_ROUTER -o ens19 -j ACCEPT
sudo iptables -A FORWARD -i ens19 -o $EXTERNAL_INTERFACE_ROUTER -j ACCEPT
sudo iptables -t nat -A PREROUTING -p tcp --dport 881 -j DNAT --to-destination 1.1.1.3:22
sudo iptables -t nat -A POSTROUTING -p tcp -d 1.1.1.3 --dport 22 -j MASQUERADE

# Allow incoming SSH to Proxmox (from ALLOWED_IPS_ROUTER) on the EXTERNAL port
for ip in "${ALLOWED_IPS_ROUTER[@]}"; do
  sudo iptables -A INPUT -i $EXTERNAL_INTERFACE_ROUTER -p tcp --dport $SSH_EXTERNAL_PORT_ROUTER -s "$ip" -j ACCEPT
  sudo iptables -A INPUT -i $EXTERNAL_INTERFACE_ROUTER -s "$ip" -j ACCEPT
done

